[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2018"
authors = ["Lukas Hedegaard <lukasxhedegaard@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
